### ISSUE TITLE
Decoder?

### ISSUE THREAD

**Issue by shawaj** [RAKWireless/RAK2270-Sticker-Tracker#1]
Hi there,

Can you share the decoder for the sticker please?

Thanks

**Comment by danak6jq** [comment]
I don't actually see a firmware file in the repo (perhaps I'm not looking hard enough). Upside - you can use RUI3 and define your own firmware very easily.

**Comment by carlrakwireless** [comment]
Hi @shawaj @danak6jq,

The firmware will be shared soon as well as the decoder 👍🏽

**Comment by shawaj** [comment]
Thanks @carlrakwireless

**Comment by shawaj** [comment]
@carlrakwireless any update on this?

**Comment by carlrakwireless** [comment]
Hi @shawaj ,

We will be posting the open-source firmware very soon.

As for the decoder, you can use CayenneLPP and you will see the data of the sensors immediately.

Also use fport = 2.
