### ISSUE TITLE
Arduino New IDE 2.x not finding Installation JSON

### ISSUE THREAD

**Issue by hpssjellis** [RAKWireless/RAK2270-Sticker-Tracker#3]
The new Arduino 2.x IDE is having troubles finding the installation STM32 boards. It loads the other RAKWireless boards but not the RUI ones. It seems to load the .JSON file fine but when we search for "RAK" it does not find the ```RAKwireless RUI STM32``` Boards. I am find since I can use the old Arduino IDE, just wondering if the new Arduino IDE works for anyone else.

```
https://raw.githubusercontent.com/RAKWireless/RAKwireless-Arduino-BSP-Index/main/package_rakwireless.com_rui_index.json
```

The Old Arduino IDE 1.8.x works fine, just search for ```RAK``` and the boards are found

**Comment by carlrakwireless** [comment]
Hi @hpssjellis ,

It my setup, I see the RAK RUI3 based modules.

![image](https://github.com/RAKWireless/RAK2270-Sticker-Tracker/assets/72064743/49630e84-3277-4970-b548-7b5a0971dea1)

I do not use Arduino 2.x though as a still find legacy Arduino IDE faster/leaner to use.

**Comment by hpssjellis** [comment]
Hey @carlrakwireless. Good to know it does works for someone. I have tried 3 Arduino IDE v2 with no luck even though the other RAKwireless .json file works fine.  I do have the old Arduino IDE on some of my computers so I should be fine. I will tag you on a few more issues. We can close this one.
