### ISSUE TITLE
Which board is compatible to the RAK2270 is it WisDuo RAK3172 E or T

### ISSUE THREAD

**Issue by hpssjellis** [RAKWireless/RAK2270-Sticker-Tracker#4]
**Which board is compatible to the RAK2270 is it WisDuo RAK3172 E or T**

@carlrakwireless  Is the compatible board the WisDuo  RAK3172 Evaluation board or the WisDuo RAK3172 T Board

![image](https://github.com/RAKWireless/RAK2270-Sticker-Tracker/assets/5605614/ce23cf51-e46f-4358-b1cf-631e6970ba91)

**Comment by carlrakwireless** [comment]
It should be `WisDuo RAK3172-SiP Board`.

**Comment by hpssjellis** [comment]
> It should be `WisDuo RAK3172-SiP Board`.

I agree, but that isn't one of the options in the image. The image shows the WisDuo RACK3**2**72-SiP board.  


```
The main chip used on the RAK2270 is the WisDuo Module RAK3172-SiP/RAK3172LP-SiP (pin-to-pin and software compatible). This chip has STM32WL SoC which is a combination of MCU and LoRa/SubGhz transceiver. The firmware written on this is based on [RUI3](https://docs.rakwireless.com/RUI3/). You can start creating your own firmware using this [RAK3172-SiP guide](https://docs.rakwireless.com/Product-Categories/WisDuo/RAK3172-SiP/Quickstart/#rak3172-sip-as-a-stand-alone-device-using-rui3).
```

**Comment by carlrakwireless** [comment]
I see. You can choose `RAK3272-SiP Board`. It will work fine.

**Comment by hpssjellis** [comment]
Sounds, good thanks.
