### ISSUE TITLE
Example Acceleration code for the RAK2270

### ISSUE THREAD

**Issue by hpssjellis** [RAKWireless/RAK2270-Sticker-Tracker#5]
**Example Acceleration code for the RAK2270**

@carlrakwireless  

Where would I find example Acceleration code for the RAK2270?

It looks like it is fairly simple I2C communication

![image](https://github.com/RAKWireless/RAK2270-Sticker-Tracker/assets/5605614/3475c3db-619e-4613-a377-271d765a6b00)

**Comment by carlrakwireless** [comment]
Hi @hpssjellis ,

The 3-axis accelerometer is based on RAK1904.

You can follow this guide for its basic functionality.

https://docs.rakwireless.com/Product-Categories/WisBlock/RAK1904/Quickstart/#software-configuration-and-example
