### ISSUE TITLE
Generic RAK2270 Firmware

### ISSUE THREAD

**Issue by hpssjellis** [RAKWireless/RAK2270-Sticker-Tracker#6]
Any chance a generic RAK2270 firmware with version number could be posted.

@carlrakwireless 

It would be really interesting to see what compression method is used, how it is done and if the present firmware has any download read ability (To perhaps change the data upload rate etc.). Also to see how the temperature value is read and if the accelerometer is initiated (Probably not)

**Comment by carlrakwireless** [comment]
I already replied in RAK forum. Closing.
